version: "3.9"

services:
  db:
    image: postgres:16
    container_name: go_job_queue_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
      POSTGRES_DB: jobqueue
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobuser -d jobqueue"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
